name: Performance report for Location redis check

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'testSuite for Location redis check'
        required: true
        default: 'towbook.LocationSuiteSimulation'
      baseUrl:
        type: string
        description: 'Base URL'
        required: true
        default: 'http://localhost'
      apiToken:
        type: string
        description: 'Api token'
        required: true
        default: 'a1bea768bdf4764656812c206c60589b50983b5c0a6cb345da89aff3393540b1be'
      rampTo:
        type: string
        description: 'Ramp users to'
        required: true
        default: '10'
      rampTime:
        type: string
        description: 'Ramp time (minutes)'
        required: true
        default: '1'
      concurrent:
        type: string
        description: 'Concurrent users'
        required: true
        default: '20'
      concurrentTime:
        type: string
        description: 'Concurrent time (minutes)'
        required: true
        default: '3'

jobs:
  execpokemonapi:
    runs-on: ubuntu-latest
    name: Execution Performance Location redis check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DbaseUrl=${{ inputs.baseUrl }} -DapiToken=${{ inputs.apiToken }} -DrampTo=${{ inputs.rampTo }} -DrampTime=${{ inputs.rampTime }} -DconcurrentUsers=${{ inputs.concurrent }} -DconcurrentTime=${{ inputs.concurrentTime }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gatling report
          path: ./build/reports/gatling
