name: Performance with publish for Location redis check

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'testSuite for Location redis check'
        required: true
        default: 'towbook.LocationSuiteSimulation'
      baseUrl:
        type: string
        description: 'Base URL'
        required: true
        default: 'http://localhost'
      apiToken:
        type: string
        description: 'Api token'
        required: true
        default: 'a1bea768bdf4764656812c206c60589b50983b5c0a6cb345da89aff3393540b1be'
      rampTime:
        type: string
        description: 'Ramp time'
        required: true
        default: '30'
      rampTo:
        type: string
        description: 'Ramp users to'
        required: true
        default: '10'
      concurrentTime:
        type: string
        description: 'Concurrent time'
        required: true
        default: '60'
      concurrent:
        type: string
        description: 'Concurrent users'
        required: true
        default: '20'

jobs:
  execpokemonapi:
    runs-on: ubuntu-latest
    name: Execution Performance Location redis check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DbaseUrl=${{ inputs.baseUrl }} -DapiToken=${{ inputs.apiToken }} -DrampTime=${{ inputs.rampTime }} -DrampTo=${{ inputs.rampTo }} -DconcurrentTime=${{ inputs.concurrentTime }} -DconcurrentUsers=${{ inputs.concurrent }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gatling report
          path: ./build/reports/gatling
      - name: "Publish test results"
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build/reports/gatling'
          keep_files: true
          user_name: yecid-rodriguez-mojix-com
          user_email: yecid.rodriguez@mojix.com
          publish_branch: gh_page
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build/reports/gatling

